//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StraatrovenEntities : DbContext
    {
        public StraatrovenEntities()
            : base("name=StraatrovenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<overvallen> overvallen { get; set; }
        public virtual DbSet<werkzoekende> werkzoekende { get; set; }
    
        public virtual ObjectResult<wz15_Result> wz15()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wz15_Result>("wz15");
        }
    
        public virtual ObjectResult<wz20_Result> wz20()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wz20_Result>("wz20");
        }
    }
}
