//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StraatrovenEntities : DbContext
    {
        public StraatrovenEntities()
            : base("name=StraatrovenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<overvallen> overvallen { get; set; }
        public virtual DbSet<werkzoekende> werkzoekende { get; set; }
        public virtual DbSet<ov> ov { get; set; }
    
        public virtual ObjectResult<hspA_Result> hspA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hspA_Result>("hspA");
        }
    
        public virtual ObjectResult<Procedure_Result> Procedure(Nullable<int> param1, Nullable<int> param2)
        {
            var param1Parameter = param1.HasValue ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(int));
    
            var param2Parameter = param2.HasValue ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Procedure_Result>("Procedure", param1Parameter, param2Parameter);
        }
    
        public virtual ObjectResult<wz16_Result> wz16()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wz16_Result>("wz16");
        }
    
        public virtual ObjectResult<wzA_Result> wzA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<wzA_Result>("wzA");
        }
    }
}
