//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class overvallen
    {
        public string voorval_nr { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> uur { get; set; }
        public string dagsoort { get; set; }
        public string dagdeel { get; set; }
        public string dagdeel_naam { get; set; }
        public string plaats { get; set; }
        public Nullable<int> district { get; set; }
        public string district_naam { get; set; }
        public int buurt { get; set; }
        public string subbuurt { get; set; }
        public string straat { get; set; }
        public string opgelost { get; set; }
    }
}
