//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weer
    {
        public System.DateTime datum { get; set; }
        public int uur { get; set; }
        public int gem_windsnelheid { get; set; }
        public int temp { get; set; }
        public int zon { get; set; }
        public int zicht { get; set; }
        public int bewolking { get; set; }
        public bool mist { get; set; }
        public bool regen { get; set; }
        public bool sneeuw { get; set; }
        public bool onweer { get; set; }
        public bool ijsvorming { get; set; }
    }
}
