//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class werkzoekende
    {
        public string buurt_code { get; set; }
        public Nullable<int> gem_nr { get; set; }
        public Nullable<int> wijk_buurt { get; set; }
        public string wijk_code { get; set; }
        public Nullable<int> wijk_nr { get; set; }
        public string wijk_naam { get; set; }
        public int buurt_nr { get; set; }
        public string buurt_naam { get; set; }
        public int werkzoekende1 { get; set; }
        public int leeftijd { get; set; }
        public string gem_naam { get; set; }
    }
}
